{"uuid": "8d82f2eb-54b9-4a28-a677-e468055d9501", "children": ["8e1c7496-6b13-4495-888b-b9469d7750a8"], "befores": [{"name": "app_page", "status": "passed", "start": 1675420330612, "stop": 1675420335881}], "afters": [{"name": "app_page::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'D:\\\\Users\\\\laixinhua\\\\AppData\\\\Local\\\\Android\\\\android-sdk\\\\platform-tools\\\\adb.exe -P 5037 -s emulator-5554 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy'' exited with code 3221226091'; Command output: <empty>\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'D:\\\\Users\\\\laixinhua\\\\AppData\\\\Local\\\\Android\\\\android-sdk\\\\platform-tools\\\\adb.exe -P 5037 -s emulator-5554 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy'' exited with code 3221226091'; Command output: <empty>\n    at getResponseForW3CError (C:\\Users\\laixinhua\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:804:9)\n    at asyncHandler (C:\\Users\\laixinhua\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\protocol.js:380:37)\n", "trace": "  File \"E:\\Users\\laixinhua\\PycharmProjects\\LittleBearAutoTest\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"E:\\Users\\laixinhua\\PycharmProjects\\LittleBearAutoTest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"E:\\Users\\laixinhua\\PycharmProjects\\LittleBearAutoTest\\conftest.py\", line 31, in app_page\n    driver.quit()\n  File \"E:\\Users\\laixinhua\\PycharmProjects\\LittleBearAutoTest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 950, in quit\n    self.execute(Command.QUIT)\n  File \"E:\\Users\\laixinhua\\PycharmProjects\\LittleBearAutoTest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 425, in execute\n    self.error_handler.check_response(response)\n  File \"E:\\Users\\laixinhua\\PycharmProjects\\LittleBearAutoTest\\venv\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 30, in check_response\n    raise wde\n  File \"E:\\Users\\laixinhua\\PycharmProjects\\LittleBearAutoTest\\venv\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 26, in check_response\n    super().check_response(response)\n  File \"E:\\Users\\laixinhua\\PycharmProjects\\LittleBearAutoTest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1675420363118, "stop": 1675420363297}], "start": 1675420330612, "stop": 1675420363297}